spring:
  datasource:
    url: jdbc:mysql://localhost:3306/where_wear
    username: root
    password: hanbit
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dc4b883de593360fff4b640fbd1a3a84
            client-secret: KKP6sbqYoJa1KSK9vh3sUPUXVNTxMEZg
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
                - profile_nickname
                - profile_image
                - account_email
            client-authentication-method: client_secret_post

          google:
            client-id: 342272538100-v6urhgemke4lk1ocnaudibdlrjg52vtd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  issuer: joungeun0825@gmail.com
  secret_key: wherewear-springboot
