spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  sql:
    init:
      encoding: UTF-8
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dc4b883de593360fff4b640fbd1a3a84
            client-secret: KKP6sbqYoJa1KSK9vh3sUPUXVNTxMEZg
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
                - profile_nickname
                - profile_image
                - account_email
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  issuer: joungeun0825@gmail.com
  secret_key: wherewear-springboot
